global using Ardalis.Specification;
global using Ardalis.Specification.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Nabs.Scenarios;
global using System.Linq.Expressions;
global using System.Reflection;
